Repository beego/beego, pull requests merged in 2022-05, with the labels that each got.

#4931 Update ini.go
  core/config/ini.go
Labels: Skip Changelog

#4940 Fix: Append column comments to `create table` sentence when using postgres
  CHANGELOG.md
  client/orm/model_test.go
  client/orm/models.go
Labels: activity/weopen-star

#4953 Refactor ORM: rename _modelCache struct to modelCache
  client/orm/cmd.go
  client/orm/db.go
  client/orm/db_utils.go
  client/orm/filter_orm_decorator.go
  client/orm/model_utils_test.go
  client/orm/models.go
  client/orm/models_boot.go
  client/orm/orm.go
  client/orm/orm_raw.go
  client/orm/orm_test.go
Labels: Skip Changelog, activity/weopen-star

#4950 Feat: add orm opentelemetry filter
  CHANGELOG.md
  client/orm/filter/opentelemetry/filter.go
  client/orm/filter/opentelemetry/filter_test.go
  go.mod
  go.sum
Labels: activity/weopen-star
